const cars = [
  {
    id: 1,
    model: "Golf GTI",
    year: 2023,
    price: 38990,
    engine: "2.0L Turbo",
    horsepower: 245,
    transmission: "Automatic DSG",
    fuel: "Petrol",
    image: "images/golf-gti.jpg",
    description: "Iconic sporty hatchback combining performance and style."
  },
  {
    id: 2,
    model: "Passat",
    year: 2023,
    price: 32990,
    engine: "1.5L Turbo",
    horsepower: 150,
    transmission: "Manual",
    fuel: "Petrol",
    image: "images/passat-lol.jpg",
    description: "Comfortable family sedan with modern features."
  },
  {
    id: 3,
    model: "ID.4",
    year: 2023,
    price: 45990,
    engine: "Electric Motor",
    horsepower: 201,
    transmission: "Automatic",
    fuel: "Electric",
    image: "images/id4.jpg",
    description: "All-electric SUV with impressive range and tech."
  },
  {
    id: 4,
    model: "Polo",
    year: 2023,
    price: 19990,
    engine: "1.0L Turbo",
    horsepower: 95,
    transmission: "Manual",
    fuel: "Petrol",
    image: "images/polo.jpg",
    description: "Compact and efficient city car."
  },
  {
    id: 5,
    model: "Tiguan",
    year: 2023,
    price: 35990,
    engine: "2.0L Diesel",
    horsepower: 150,
    transmission: "Automatic",
    fuel: "Diesel",
    image: "images/tiguan.jpg",
    description: "Versatile SUV for family adventures."
  },
  {
    id: 6,
    model: "Arteon",
    year: 2023,
    price: 41990,
    engine: "2.0L Turbo",
    horsepower: 190,
    transmission: "Automatic DSG",
    fuel: "Petrol",
    image: "images/arteon.jpg",
    description: "Elegant fastback with premium interior."
  },
  {
    id: 7,
    model: "Touareg",
    year: 2023,
    price: 69990,
    engine: "3.0L V6 Diesel",
    horsepower: 286,
    transmission: "Automatic",
    fuel: "Diesel",
    image: "images/touareg.jpg",
    description: "Luxury SUV with off-road capabilities and premium comfort."
  },
  {
    id: 8,
    model: "Golf R",
    year: 2023,
    price: 52990,
    engine: "2.0L Turbo",
    horsepower: 320,
    transmission: "Automatic DSG",
    fuel: "Petrol",
    image: "images/golf-r.jpg",
    description: "High-performance version of the Golf with all-wheel drive."
  },
  {
    id: 9,
    model: "ID.3",
    year: 2023,
    price: 39990,
    engine: "Electric Motor",
    horsepower: 204,
    transmission: "Automatic",
    fuel: "Electric",
    image: "images/id3.jpg",
    description: "Compact electric hatchback with modern design."
  },
  {
    id: 10,
    model: "T-Roc",
    year: 2023,
    price: 28990,
    engine: "1.5L Turbo",
    horsepower: 150,
    transmission: "Manual",
    fuel: "Petrol",
    image: "images/t-roc.jpg",
    description: "Stylish compact SUV with urban appeal."
  },
  {
    id: 11,
    model: "Sharan",
    year: 2023,
    price: 44990,
    engine: "2.0L Diesel",
    horsepower: 150,
    transmission: "Automatic DSG",
    fuel: "Diesel",
    image: "images/sharan.jpg",
    description: "Spacious family MPV with sliding doors."
  },
  {
    id: 12,
    model: "Caddy",
    year: 2023,
    price: 31990,
    engine: "2.0L Diesel",
    horsepower: 122,
    transmission: "Manual",
    fuel: "Diesel",
    image: "images/caddy.jpg",
    description: "Versatile commercial vehicle perfect for business use."
  },
  {
    id: 13,
    model: "Amarok",
    year: 2023,
    price: 49990,
    engine: "3.0L V6 Diesel",
    horsepower: 224,
    transmission: "Automatic",
    fuel: "Diesel",
    image: "images/amarok.jpg",
    description: "Robust pickup truck for work and adventure."
  },
  {
    id: 14,
    model: "Taos",
    year: 2023,
    price: 32990,
    engine: "1.5L Turbo",
    horsepower: 158,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "images/taos.jpg",
    description: "Compact crossover SUV with modern features."
  },
  {
    id: 15,
    model: "Atlas",
    year: 2023,
    price: 41990,
    engine: "2.0L Turbo",
    horsepower: 235,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "images/atlas.jpg",
    description: "Large family SUV with three rows of seating."
  }
];
