const languages = {
  en: {
    title: "Volkswagen Model Finder",
    subtitle: "Find your perfect Volkswagen",
    searchPlaceholder: "Search by model...",
    allFuels: "All Fuels",
    maxPrice: "Max Price (€)",
    minYear: "Min Year",
    sortBy: "Sort by...",
    priceLowToHigh: "Price: Low to High",
    priceHighToLow: "Price: High to Low",
    newestFirst: "Newest First",
    oldestFirst: "Oldest First",
    mostPowerful: "Most Powerful",
    leastPowerful: "Least Powerful",
    carQuiz: "🚗 Car Quiz",
    darkMode: "🌙 Dark Mode",
    lightMode: "☀️ Light Mode",
    calculator: "💰 Calculator",
    favorites: "Favorites",
    compare: "Compare",
    clearFavorites: "Clear Favorites",
    clearCompare: "Clear Compare",
    viewDetails: "View Details",
    year: "Year",
    price: "Price",
    engine: "Engine",
    horsepower: "Horsepower",
    transmission: "Transmission",
    fuel: "Fuel",
    rating: "Rating",
    reviews: "reviews",
    customerReviews: "Customer Reviews",
    noReviews: "No reviews yet. Be the first to review!",
    addReview: "Add Your Review",
    selectRating: "Select rating",
    shareThoughts: "Share your thoughts about this car...",
    submitReview: "Submit Review",
    carComparison: "Car Comparison",
    takeQuizAgain: "Take Quiz Again",
    quizComplete: "Quiz Complete!",
    finalScore: "Final Score:",
    excellent: "🏆 Excellent! You're a Volkswagen expert!",
    goodJob: "👍 Good job! You know your Volkswagens!",
    keepLearning: "📚 Keep learning about Volkswagen cars!",
    carFinancingCalculator: "Car Financing Calculator",
    carPrice: "Car Price (€)",
    downPayment: "Down Payment (€)",
    loanTerm: "Loan Term (years)",
    interestRate: "Interest Rate (%)",
    calculate: "Calculate",
    monthlyPayment: "Monthly Payment:",
    totalLoanAmount: "Total Loan Amount:",
    totalInterest: "Total Interest:",
    totalPayment: "Total Payment:",
    dealerships: "🏢 Dealerships",
    language: "🌐 Language",
    english: "English",
    finnish: "Suomi",
    noFavorites: "No favorites added yet!",
    selectTwoCars: "Please select 2 cars to compare!",
    maxTwoCars: "You can compare maximum 2 cars at a time.",
    confirmClearFavorites: "Are you sure you want to clear all favorites?",
    confirmClearCompare: "Are you sure you want to clear all compared cars?",
    reviewSubmitted: "Review submitted successfully!",
    failedSubmitReview: "Failed to submit review. Please try again.",
    errorSubmitReview: "Error submitting review. Please try again."
  },
  fi: {
    title: "Volkswagen Mallietsin",
    subtitle: "Löydä täydellinen Volkswagen",
    searchPlaceholder: "Hae mallin mukaan...",
    allFuels: "Kaikki polttoaineet",
    maxPrice: "Maksimi hinta (€)",
    minYear: "Min. vuosi",
    sortBy: "Järjestä...",
    priceLowToHigh: "Hinta: Halvin ensin",
    priceHighToLow: "Hinta: Kallein ensin",
    newestFirst: "Uusin ensin",
    oldestFirst: "Vanhin ensin",
    mostPowerful: "Tehokkain",
    leastPowerful: "Heikoin",
    carQuiz: "🚗 Auto-visa",
    darkMode: "🌙 Tumma tila",
    lightMode: "☀️ Vaalea tila",
    calculator: "💰 Laskin",
    favorites: "Suosikit",
    compare: "Vertaile",
    clearFavorites: "Tyhjennä suosikit",
    clearCompare: "Tyhjennä vertailu",
    viewDetails: "Näytä tiedot",
    year: "Vuosi",
    price: "Hinta",
    engine: "Moottori",
    horsepower: "Hevosvoimat",
    transmission: "Vaihteisto",
    fuel: "Polttoaine",
    rating: "Arvosana",
    reviews: "arvostelua",
    customerReviews: "Asiakasarvostelut",
    noReviews: "Ei arvosteluja vielä. Ole ensimmäinen!",
    addReview: "Lisää arvostelu",
    selectRating: "Valitse arvosana",
    shareThoughts: "Jaa ajatuksesi tästä autosta...",
    submitReview: "Lähetä arvostelu",
    carComparison: "Autojen vertailu",
    takeQuizAgain: "Ota visa uudelleen",
    quizComplete: "Visa valmis!",
    finalScore: "Lopullinen tulos:",
    excellent: "🏆 Erinomaista! Olet Volkswagen-asiantuntija!",
    goodJob: "👍 Hyvää työtä! Tunnet Volkswagenit!",
    keepLearning: "📚 Jatka Volkswagenien opiskelua!",
    carFinancingCalculator: "Auton rahoituslaskin",
    carPrice: "Auton hinta (€)",
    downPayment: "Käsiraha (€)",
    loanTerm: "Laina-aika (vuotta)",
    interestRate: "Korko (%)",
    calculate: "Laske",
    monthlyPayment: "Kuukausierä:",
    totalLoanAmount: "Lainasumma yhteensä:",
    totalInterest: "Korkokustannukset yhteensä:",
    totalPayment: "Maksu yhteensä:",
    dealerships: "🏢 Jälleenmyyjät",
    language: "🌐 Kieli",
    english: "English",
    finnish: "Suomi",
    noFavorites: "Ei suosikkeja vielä!",
    selectTwoCars: "Valitse 2 autoa vertailuun!",
    maxTwoCars: "Voit vertailla korkeintaan 2 autoa kerrallaan.",
    confirmClearFavorites: "Haluatko varmasti tyhjentää kaikki suosikit?",
    confirmClearCompare: "Haluatko varmasti tyhjentää kaikki vertailtavat autot?",
    reviewSubmitted: "Arvostelu lähetetty onnistuneesti!",
    failedSubmitReview: "Arvostelun lähetys epäonnistui. Yritä uudelleen.",
    errorSubmitReview: "Virhe arvostelun lähetyksessä. Yritä uudelleen."
  }
};
